### ISSUE TITLE
Deduplicate ZIM tag values

### ISSUE THREAD

**Issue by benoit74** [openzim/python-scraperlib#156]
When computing the list of tags, it could help to deduplicate them, so that they are not "doubled" by mistake.

https://github.com/openzim/ted/blob/60fb82a127b371907c8d24ba70b4e50d29ff5005/src/ted2zim/scraper.py#L93

**Comment by dan-niles** [comment]
@benoit74 Sure, I'm up for it.
I think we can remove the duplicates inside the [config_metadata](https://github.com/openzim/python-scraperlib/blob/main/src/zimscraperlib/zim/creator.py#L213) function in the the scraperlib code.

I noticed that some scrapers like `ted` and `youtube` use the [make_zim_file](https://github.com/openzim/python-scraperlib/blob/main/src/zimscraperlib/zim/filesystem.py#L115) function from scraperlib, which initializes a [Creator](https://github.com/openzim/python-scraperlib/blob/main/src/zimscraperlib/zim/creator.py#L88) object and calls the `config_metadata` method.
While `warc2zim` and `kolibri` initialize a [Creator](https://github.com/openzim/python-scraperlib/blob/main/src/zimscraperlib/zim/creator.py#L88) object and calls the `config_metadata` method directly.

Since these scrapers eventually end up calling the `config_metadata` method, I think if we do the deduplication there, we only have to update in one place. What do you think?

**Comment by benoit74** [comment]
Yep, this makes sense. Good observations!

**Comment by benoit74** [comment]
Strongly related to #164, should be implemented together
